## check the ssl cert value in line number 9, check in the aws lb
## you would need to request a certificate in aws, use a DNS verification to request cert, make cname dns entries to complete the validation, which will enable the
## cert available for NLB (visible when you create listener), note the certificate value and update in this file.

controller:
  service:
    httpPort:
      targetPort: 80
    httpsPort:
      targetPort: 80
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:897722697588:certificate/56502e6b-8669-418c-b292-b24ece91832e
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"